// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK3Qx-pzJopBMpXCA5Y7_CJQxru8ieyEw',
    appId: '1:309786849815:web:d81aa64e4a08b75ceda252',
    messagingSenderId: '309786849815',
    projectId: 'notex-5c4ce',
    authDomain: 'notex-5c4ce.firebaseapp.com',
    storageBucket: 'notex-5c4ce.appspot.com',
    measurementId: 'G-06SMHFYJ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknoItQNFKP2X9ODKhmXrK9WfMxudxkxg',
    appId: '1:309786849815:android:53161753c68ef53ceda252',
    messagingSenderId: '309786849815',
    projectId: 'notex-5c4ce',
    storageBucket: 'notex-5c4ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-iI1kOxSqMLw3vTuD-vCjmW7gfmYD-Dg',
    appId: '1:309786849815:ios:e72fa42ec86abf27eda252',
    messagingSenderId: '309786849815',
    projectId: 'notex-5c4ce',
    storageBucket: 'notex-5c4ce.appspot.com',
    iosClientId: '309786849815-vh053hp3d2hofh58qj8gc64o4ka2n4oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.notex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-iI1kOxSqMLw3vTuD-vCjmW7gfmYD-Dg',
    appId: '1:309786849815:ios:e72fa42ec86abf27eda252',
    messagingSenderId: '309786849815',
    projectId: 'notex-5c4ce',
    storageBucket: 'notex-5c4ce.appspot.com',
    iosClientId: '309786849815-vh053hp3d2hofh58qj8gc64o4ka2n4oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.notex',
  );
}
